# Generated by Django 4.2.15 on 2024-09-02 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('founder', 'Founder'), ('joining', 'Joining a team'), ('undecided', 'Undecided')], max_length=50)),
                ('bio_interests', models.TextField()),
                ('bio_background', models.TextField()),
                ('bio_projects', models.TextField()),
            ],
        ),
    ]
